### ISSUE TITLE
Fails on FastClick

### ISSUE THREAD

**Issue by websirnik** [StoryCloud/webkit-assign#7]
I'm using webkit-assign with Gulp. I process all my dependencies in one pipe.
When I include [FastClick](https://github.com/ftlabs/fastclick) in the dependency list. Gulp exits with error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'type' of null
    at .../app/node_modules/webkit-assign/index.js:70:17
    at traverse (.../app/node_modules/webkit-assign/index.js:37:5)
    at .../app/node_modules/webkit-assign/index.js:42:21
    at arrayEach (...app/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (.../app/node_modules/lodash/index.js:3345:13)
    at .../app/node_modules/webkit-assign/index.js:41:19
    at .../app/node_modules/lodash/index.js:3073:15
    at baseForOwn (.../app/node_modules/lodash/index.js:2046:14)
    at Function.forOwn (../app/node_modules/lodash/index.js:3378:16)
    at traverse (.../app/node_modules/webkit-assign/index.js:38:7)
```

**Comment by jacksonrayhamilton** [comment]
Thanks, we will investigate. Which version of FastClick?

**Comment by websirnik** [comment]
1.0.6

**Comment by JorritPosthuma** [comment]
This is a problem I also ran into, and fixed in https://github.com/StoryCloud/webkit-assign/pull/8. We saw it with a different library. But it might be the case that my fix only hides a more complex problem: https://github.com/nolemmings/webkit-assign/blob/master/index.js#L70
